### ISSUE TITLE
Windows binaries (32-/64 bit) for your chess program

### ISSUE THREAD

**Issue by yellow-panther** [Highhand/Karotten#1]
Hello Highhand,
can you create Windows binaries (32-/64 bit) please and host these files on GitHub, too?

GUIs cf. http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list

**Comment by simka275** [comment]
Sorry for the late answer... I'd rather not host binaries on this repo but you can easily the compile the code yourself with for example MinGW.

**Comment by yellow-panther** [comment]
Sorry, but I am not a programmer..... can you send me the .exe(s) to yellowpanther304@gmail.com please?
Gmail accepts no .exe, .rar or zip files, but you can change the extensions easily with Ant Renamer http://www.antp.be/software/renamer e.g. from .zip into .zap or .rar into .rir
